### PR TITLE
Update for Python3

### PR DESCRIPTION
**Pull request by Martoni**
Just few modification to run it with Python3.

### CODE REVIEW

**Comment by vpelletier** [comment]
Thanks, the changes look good and `2to3` failed to pick them up, so a source change is indeed needed. I will rework them a tiny bit to preserve python 2 compatibility.

One change I do not understand though is the removal of `.value` on `getFeatureReport`'s `return` statement. What is the intent behind it ?

**Comment by Martoni** [comment]
Hi Vincent,

On 12/12/2016 23:46, Vincent Pelletier wrote:
>
> Thanks, the changes look good and |2to3| failed to pick them up, so a
> source change is indeed needed. I will rework them a tiny bit to
> preserve python 2 compatibility.
>
> One change I do not understand though is the removal of |.value| on
> |getFeatureReport|'s |return| statement. What is the intent behind it ?
>
I deleted .value because it not return all report values.

For example I tested this library with the usb-gpio chip CP2112
I get the report descriptor 0x02 to get GPIO configuration, the length
of report should be 4 bytes according to datasheet (AN495: CP2112
Interface Specification).
But if I return buf.value I get only 2 bytes:

self._ioctl(_HIDIOCGFEATURE(length), buf, True)
print(len(buf))
>64
print(buf)
><ctypes.c_char_Array_64 object at 0x7fbeda16bb70>
print(len(buf.value))
>2
print(buf.value)
>b'\x02\xff'

Apparently .value method truncate at the first \x00 values.

**Comment by vpelletier** [comment]
> But if I return buf.value I get only 2 bytes:

Ah, indeed, this also caught my eye but I did not think this far: I should not have used `create_string_buffer` here, as it's binary data and indeed strings are expected to be null-terminated by ctypes.

Could you try with 3858c303e2418c77cb203194e7ec623a318037d2 (current master) ?

I had to avoid using `bytes()` near ctypes, as items are integers in python3 and chars in python2.

**Comment by vpelletier** [comment]
> the «report» is not integrated in buf ;)

Woops ! And as I take its length, pylint does not complain.
Fixed.

**Comment by vpelletier** [comment]
And 1.2 released on pypi.

Thanks a lot for your report, testing and sorry for not pulling your patches verbatim.

**Comment by Martoni** [comment]
Ok, work for me.

**Pull request closed without merging**
